### ISSUE TITLE
CircleCI failing on PR builds

### ISSUE THREAD

**Issue by JRJurman** [Tram-One/tram-one#72]
## Summary
For some reason, CircleCI always fails unless repeated without cache. This happened in the PR for #69, but it could be something external as well.

**Comment by JRJurman** [comment]
```
tram-one.js → dist/tram-one.umd.js...
            [!] SyntaxError: 'with' in strict mode (10:4)
            node_modules/domino/lib/sloppy.js (10:4)
            SyntaxError: 'with' in strict mode (10:4)
                at error (/home/circleci/tram-one/node_modules/rollup/dist/rollup.js:185:14)
                at Promise.resolve.then.catch.err (/home/circleci/tram-one/node_modules/rollup/dist/rollup.js:9448:6)
```

**Comment by JRJurman** [comment]
Fixed by removing generic cache. See #71
